services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  
  my-keycloak:
    image: docker.io/keycloak/keycloak:26.2.5
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      KC_HTTP_PORT: 7080
      KC_METRICS_ENABLED: true
    env_file:
      - .env
    command: [ "start-dev", "--http-port", "7080" ]
    ports:
      - "7080:7080"
    volumes:
      - keycloak-data:/opt/keycloak/data
  
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  minio:
#    image: docker.io/bitnami/minio:latest
#    ports:
#      - '9000:9000'
#      - '9001:9001'
#    volumes:
#      - minio_data:/bitnami/minio/data
#    environment:
#      - MINIO_ROOT_USER=${MINIO_NAME}
#      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
#    #      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}
#    env_file:
#      - .env
volumes:
  postgres_data:
  keycloak-data:
  minio_data: