services:
  #  backend:
  #    build: .
  #    ports:
  #      - "8080:8080"
  #    env_file:
  #      - .env
  #    depends_on:
  #      - db
  #    environment:
  #      - DB_HOST=db
  #      - DB_PORT=5432

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

volumes:
  postgres_data:
