services:
  mailhog:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
  #  backend:
  #    build: .
  #    ports:
  #      - "8080:8080"
  #    env_file:
  #      - .env
  #    depends_on:
  #      - db
  #    environment:
  #      - DB_HOST=db
  #      - DB_PORT=5432
  
  my-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      
      KC_EMAIL_FROM: no-reply@example.com
      KC_EMAIL_FROM_DISPLAY_NAME: "Keycloak Admin"
      KC_EMAIL_REPLY_TO: support@example.com
      KC_EMAIL_REPLY_TO_DISPLAY_NAME: "Support Team"
      KC_EMAIL_SMTP_HOST: mailhog
      KC_EMAIL_SMTP_PORT: 1025
      KC_EMAIL_SMTP_AUTH: false
      KC_EMAIL_SMTP_STARTTLS: false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm" ]
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
      - keycloak-data:/opt/keycloak/data
  
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

volumes:
  postgres_data:
  keycloak-data: